(defvar ph (make-hash-table :test (q equal)))
(defvar nh (make-hash-table :test (q equal)))
(define-symbol-macro p (gethash *load-truename* ph 0))
(define-symbol-macro n (gethash *load-truename* nh 1))
(defun  snl  (s c d)  (if (== c #\lf) (setf n (+ n d) p (file-position s))) c)
(defun  off  (s)                                     (- (file-position s) p))
(defun peekc (s)                  (peek-char              nil s nil))
(defun readc (s)           (snl s (read-char                  s) 1))
(defun unrdc (s c)              (unread-char     (snl s c -1) s))
(defun readp (s)                  (read-preserving-whitespace s))
